### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by fadingchen** [xushuduo/MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI#1]
请问可以通过系统 ota 升级吗，HDMI 驱动正常吗，打算按照这个配置也整一套，有什么踩过的坑，请分享一下，感谢！  感谢分享 efi

**Comment by xushuduo** [comment]
1. 可OTA升级小版本，我这个最初镜像版本是从10.15.3，一直升至10.15.5没有问题。当前已经是最新版本，后续发布的新版本OTA升级有可能会出现问题。
2. RX590是免驱卡，目前我现在用的是DP口，HDMI也试过正常可用，可多个接口扩展显示器，可热插拔。
3. RX590目前市面上多出一个GME版本，这个版本不可免驱，暂时无解，购买时请注意！
4. 如果你需要使用WiFi上网，建议购买BCM94360CD。
