### ISSUE TITLE
无法安装完成，求助

### ISSUE THREAD

**Issue by andychucs** [xushuduo/MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI#2]
我使用的是9700k核显，其他硬件均一致，准备之后再加5700xt，但是我使用【黑果小兵】macOS Catalina 10.15.5 19F101 正式版 with Clover 5118镜像安装后无法启动，在图中位置无限重启，甚至无法重新进入安装引导项。请问你的安装流程是怎样的，过去安装黑苹果还从来没遇到过完全无法启动的情况。
![IMG_2107](https://user-images.githubusercontent.com/24852023/85301865-f97fe480-b4da-11ea-8937-c757323f0c60.PNG)

**Comment by xushuduo** [comment]
请确定以下几点：

1. BIOS的CFG Lock是否已经关闭
2. 你是通过黑果小兵的Clover引导还是Opencore引导？
3. 如果你使用我这个EFI包，进入安装系统前，除了下面几个必要的Kexts，其余都关闭了。
   - Lilu.kext
   - SMCProcessor.kext
   - SMCSuperIO.kext
   - VirtualSMC.kext
   - WhateverGreen.kext
4. 【重要】这块微星主板插U盘安装，请插主板后面的USB2.0口。
5. `CPUFriend.kext`和`CPUFriendDataProvider.kext`这两个是9600k的睿频文件，不同CPU请将其删除。

**Comment by andychucs** [comment]
> 请确定以下几点：
> 
> 1. BIOS的CFG Lock是否已经关闭
> 2. 你是通过黑果小兵的Clover引导还是Opencore引导？
> 3. 如果你使用我这个EFI包，进入安装系统前，除了下面几个必要的Kexts，其余都关闭了。
>    
>    * Lilu.kext
>    * SMCProcessor.kext
>    * SMCSuperIO.kext
>    * VirtualSMC.kext
>    * WhateverGreen.kext
> 4. 【重要】这块微星主板插U盘安装，请插主板后面的USB2.0口。
> 5. `CPUFriend.kext`和`CPUFriendDataProvider.kext`这两个是9600k的睿频文件，不同CPU请将其删除。

1. 确认关闭
2. clover
3. 我在安装完成后关闭了其他kexts切换OC引导系统会卡在苹果logo处无进度条（我理解错了，这个操作应该是安装阶段？不过现在已经不能测试了，我的主板存在内存插槽的问题已经去换货了😂）
4. 可能是主要原因，我使用了USB3.0，换到2.0似乎重启次数还是异常多，不过最终成功安装进入系统。
5. 正在尝试。
感谢回答🙏
