### ISSUE TITLE
Windows设备管理器中出现了2个未知设备

### ISSUE THREAD

**Issue by 446226323** [xushuduo/MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI#3]
你好，我使用了你的EFI目录，一切顺利，非常感谢，进入系统后我自己生成了3码，但是有个小问题，我是双系统，一个系统一个盘，在切换到Windows的时候，设备管理器中出现了2个未知设备，不知道如何解决，而且我确信是这个OC引导造成的，我通过使用U盘的clover引导进Windows则没有这个问题。

**Comment by xushuduo** [comment]
你好，因为我这边是双硬盘一个硬盘装一个系统，切换Windows是通过F11切换硬盘启动，所以一直没发现这个问题。

刚查了下，是USB定制文件放重了。解决：将`ACPI`文件夹下的`SSDT-EC.aml`、`SSDT-UIAC.aml`、`SSDT-USBX.aml`删除，同时编辑`config.plist`文件移去对应配置即可。

移去后，进Windows不会再出现2个未知设备，但会有一个错误的设备，应该是USB定制没处理好，但不影响正常使用，后续OC更版本一并解决。你也可以使用`Hackintool`工具自己定制USB端口来解决此问题。

**Comment by 446226323** [comment]
好的，谢谢，我不怎么会编辑，既然新版本可以解决，我就等新版本好了。这两个未知设备也并不会影响正常使用。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XSDCoder"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 晚上8:56
收件人: "xushuduo/MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI"<MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI@noreply.github.com&gt;; 
抄送: "徐洋"<446226323@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [xushuduo/MSI_Z390_TOMAHAWK_I5-9600K_HACKINTOSH_OPENCORE_EFI] Windows设备管理器中出现了2个未知设备 (#3)





 
你好，因为我这边是双硬盘一个硬盘装一个系统，切换Windows是通过F11切换硬盘启动，所以一直没发现这个问题。
 
刚查了下，是USB定制文件放重了。解决：将ACPI文件夹下的SSDT-EC.aml、SSDT-UIAC.aml、SSDT-USBX.aml删除，同时编辑config.plist文件移去对应配置即可。
 
移去后，进Windows不会再出现2个未知设备，但会有一个错误的设备，应该是USB定制没处理好，但不影响正常使用，后续OC更版本一并解决。你也可以使用Hackintool工具自己定制USB端口来解决此问题。
